on:
  push:
    branches: 
      - master



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "login to docker hub"
        run: docker login --username ${{ secrets.DOCKERUSER}} --password ${{ secrets.DOCKERPASS}}
      - name: "building docker image"
        run: docker build -t ${{ secrets.DOCKERUSER}}/task2image .
      - name: "push image"
        run: docker push ${{ secrets.DOCKERUSER}}/task2image
